/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SignupVerifyRouteImport } from './routes/signup/verify'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses/index'
import { Route as AuthenticatedSettingsResigninRouteImport } from './routes/_authenticated/settings/resignin'
import { Route as AuthenticatedSettingsManageSubjectsRouteImport } from './routes/_authenticated/settings/manage-subjects'
import { Route as AuthenticatedSettingsElevatedRouteImport } from './routes/_authenticated/settings/_elevated'
import { Route as AuthenticatedExpensesExpenseIdRouteRouteImport } from './routes/_authenticated/expenses/$expenseId/route'
import { Route as AuthenticatedExpensesExpenseIdIndexRouteImport } from './routes/_authenticated/expenses/$expenseId/index'
import { Route as AuthenticatedSettingsElevatedPasskeyRouteImport } from './routes/_authenticated/settings/_elevated/passkey'
import { Route as AuthenticatedExpensesExpenseIdViewRouteImport } from './routes/_authenticated/expenses/$expenseId/view'
import { Route as AuthenticatedExpensesExpenseIdItemsIndexStrRouteImport } from './routes/_authenticated/expenses/$expenseId/items.$indexStr'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupVerifyRoute = SignupVerifyRouteImport.update({
  id: '/signup/verify',
  path: '/signup/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsResigninRoute =
  AuthenticatedSettingsResigninRouteImport.update({
    id: '/settings/resignin',
    path: '/settings/resignin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsManageSubjectsRoute =
  AuthenticatedSettingsManageSubjectsRouteImport.update({
    id: '/settings/manage-subjects',
    path: '/settings/manage-subjects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsElevatedRoute =
  AuthenticatedSettingsElevatedRouteImport.update({
    id: '/settings/_elevated',
    path: '/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesExpenseIdRouteRoute =
  AuthenticatedExpensesExpenseIdRouteRouteImport.update({
    id: '/expenses/$expenseId',
    path: '/expenses/$expenseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesExpenseIdIndexRoute =
  AuthenticatedExpensesExpenseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExpensesExpenseIdRouteRoute,
  } as any)
const AuthenticatedSettingsElevatedPasskeyRoute =
  AuthenticatedSettingsElevatedPasskeyRouteImport.update({
    id: '/passkey',
    path: '/passkey',
    getParentRoute: () => AuthenticatedSettingsElevatedRoute,
  } as any)
const AuthenticatedExpensesExpenseIdViewRoute =
  AuthenticatedExpensesExpenseIdViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => AuthenticatedExpensesExpenseIdRouteRoute,
  } as any)
const AuthenticatedExpensesExpenseIdItemsIndexStrRoute =
  AuthenticatedExpensesExpenseIdItemsIndexStrRouteImport.update({
    id: '/items/$indexStr',
    path: '/items/$indexStr',
    getParentRoute: () => AuthenticatedExpensesExpenseIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/verify': typeof VerifyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/signup': typeof SignupIndexRoute
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/manage-subjects': typeof AuthenticatedSettingsManageSubjectsRoute
  '/settings/resignin': typeof AuthenticatedSettingsResigninRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/expenses/$expenseId/view': typeof AuthenticatedExpensesExpenseIdViewRoute
  '/settings/passkey': typeof AuthenticatedSettingsElevatedPasskeyRoute
  '/expenses/$expenseId/': typeof AuthenticatedExpensesExpenseIdIndexRoute
  '/expenses/$expenseId/items/$indexStr': typeof AuthenticatedExpensesExpenseIdItemsIndexStrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/verify': typeof VerifyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/signup': typeof SignupIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/manage-subjects': typeof AuthenticatedSettingsManageSubjectsRoute
  '/settings/resignin': typeof AuthenticatedSettingsResigninRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/expenses/$expenseId/view': typeof AuthenticatedExpensesExpenseIdViewRoute
  '/settings/passkey': typeof AuthenticatedSettingsElevatedPasskeyRoute
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdIndexRoute
  '/expenses/$expenseId/items/$indexStr': typeof AuthenticatedExpensesExpenseIdItemsIndexStrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/signup/': typeof SignupIndexRoute
  '/_authenticated/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRouteRouteWithChildren
  '/_authenticated/settings/_elevated': typeof AuthenticatedSettingsElevatedRouteWithChildren
  '/_authenticated/settings/manage-subjects': typeof AuthenticatedSettingsManageSubjectsRoute
  '/_authenticated/settings/resignin': typeof AuthenticatedSettingsResigninRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/expenses/$expenseId/view': typeof AuthenticatedExpensesExpenseIdViewRoute
  '/_authenticated/settings/_elevated/passkey': typeof AuthenticatedSettingsElevatedPasskeyRoute
  '/_authenticated/expenses/$expenseId/': typeof AuthenticatedExpensesExpenseIdIndexRoute
  '/_authenticated/expenses/$expenseId/items/$indexStr': typeof AuthenticatedExpensesExpenseIdItemsIndexStrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/verify'
    | '/dashboard'
    | '/signup/verify'
    | '/signup'
    | '/expenses/$expenseId'
    | '/settings'
    | '/settings/manage-subjects'
    | '/settings/resignin'
    | '/expenses'
    | '/expenses/$expenseId/view'
    | '/settings/passkey'
    | '/expenses/$expenseId/'
    | '/expenses/$expenseId/items/$indexStr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/verify'
    | '/dashboard'
    | '/signup/verify'
    | '/signup'
    | '/settings'
    | '/settings/manage-subjects'
    | '/settings/resignin'
    | '/expenses'
    | '/expenses/$expenseId/view'
    | '/settings/passkey'
    | '/expenses/$expenseId'
    | '/expenses/$expenseId/items/$indexStr'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signin'
    | '/verify'
    | '/_authenticated/dashboard'
    | '/signup/verify'
    | '/signup/'
    | '/_authenticated/expenses/$expenseId'
    | '/_authenticated/settings/_elevated'
    | '/_authenticated/settings/manage-subjects'
    | '/_authenticated/settings/resignin'
    | '/_authenticated/expenses/'
    | '/_authenticated/settings/'
    | '/_authenticated/expenses/$expenseId/view'
    | '/_authenticated/settings/_elevated/passkey'
    | '/_authenticated/expenses/$expenseId/'
    | '/_authenticated/expenses/$expenseId/items/$indexStr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
  VerifyRoute: typeof VerifyRoute
  SignupVerifyRoute: typeof SignupVerifyRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/verify': {
      id: '/signup/verify'
      path: '/signup/verify'
      fullPath: '/signup/verify'
      preLoaderRoute: typeof SignupVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/resignin': {
      id: '/_authenticated/settings/resignin'
      path: '/settings/resignin'
      fullPath: '/settings/resignin'
      preLoaderRoute: typeof AuthenticatedSettingsResigninRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/manage-subjects': {
      id: '/_authenticated/settings/manage-subjects'
      path: '/settings/manage-subjects'
      fullPath: '/settings/manage-subjects'
      preLoaderRoute: typeof AuthenticatedSettingsManageSubjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/_elevated': {
      id: '/_authenticated/settings/_elevated'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsElevatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/$expenseId': {
      id: '/_authenticated/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/$expenseId/': {
      id: '/_authenticated/expenses/$expenseId/'
      path: '/'
      fullPath: '/expenses/$expenseId/'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdIndexRouteImport
      parentRoute: typeof AuthenticatedExpensesExpenseIdRouteRoute
    }
    '/_authenticated/settings/_elevated/passkey': {
      id: '/_authenticated/settings/_elevated/passkey'
      path: '/passkey'
      fullPath: '/settings/passkey'
      preLoaderRoute: typeof AuthenticatedSettingsElevatedPasskeyRouteImport
      parentRoute: typeof AuthenticatedSettingsElevatedRoute
    }
    '/_authenticated/expenses/$expenseId/view': {
      id: '/_authenticated/expenses/$expenseId/view'
      path: '/view'
      fullPath: '/expenses/$expenseId/view'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdViewRouteImport
      parentRoute: typeof AuthenticatedExpensesExpenseIdRouteRoute
    }
    '/_authenticated/expenses/$expenseId/items/$indexStr': {
      id: '/_authenticated/expenses/$expenseId/items/$indexStr'
      path: '/items/$indexStr'
      fullPath: '/expenses/$expenseId/items/$indexStr'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdItemsIndexStrRouteImport
      parentRoute: typeof AuthenticatedExpensesExpenseIdRouteRoute
    }
  }
}

interface AuthenticatedExpensesExpenseIdRouteRouteChildren {
  AuthenticatedExpensesExpenseIdViewRoute: typeof AuthenticatedExpensesExpenseIdViewRoute
  AuthenticatedExpensesExpenseIdIndexRoute: typeof AuthenticatedExpensesExpenseIdIndexRoute
  AuthenticatedExpensesExpenseIdItemsIndexStrRoute: typeof AuthenticatedExpensesExpenseIdItemsIndexStrRoute
}

const AuthenticatedExpensesExpenseIdRouteRouteChildren: AuthenticatedExpensesExpenseIdRouteRouteChildren =
  {
    AuthenticatedExpensesExpenseIdViewRoute:
      AuthenticatedExpensesExpenseIdViewRoute,
    AuthenticatedExpensesExpenseIdIndexRoute:
      AuthenticatedExpensesExpenseIdIndexRoute,
    AuthenticatedExpensesExpenseIdItemsIndexStrRoute:
      AuthenticatedExpensesExpenseIdItemsIndexStrRoute,
  }

const AuthenticatedExpensesExpenseIdRouteRouteWithChildren =
  AuthenticatedExpensesExpenseIdRouteRoute._addFileChildren(
    AuthenticatedExpensesExpenseIdRouteRouteChildren,
  )

interface AuthenticatedSettingsElevatedRouteChildren {
  AuthenticatedSettingsElevatedPasskeyRoute: typeof AuthenticatedSettingsElevatedPasskeyRoute
}

const AuthenticatedSettingsElevatedRouteChildren: AuthenticatedSettingsElevatedRouteChildren =
  {
    AuthenticatedSettingsElevatedPasskeyRoute:
      AuthenticatedSettingsElevatedPasskeyRoute,
  }

const AuthenticatedSettingsElevatedRouteWithChildren =
  AuthenticatedSettingsElevatedRoute._addFileChildren(
    AuthenticatedSettingsElevatedRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesExpenseIdRouteRoute: typeof AuthenticatedExpensesExpenseIdRouteRouteWithChildren
  AuthenticatedSettingsElevatedRoute: typeof AuthenticatedSettingsElevatedRouteWithChildren
  AuthenticatedSettingsManageSubjectsRoute: typeof AuthenticatedSettingsManageSubjectsRoute
  AuthenticatedSettingsResigninRoute: typeof AuthenticatedSettingsResigninRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesExpenseIdRouteRoute:
    AuthenticatedExpensesExpenseIdRouteRouteWithChildren,
  AuthenticatedSettingsElevatedRoute:
    AuthenticatedSettingsElevatedRouteWithChildren,
  AuthenticatedSettingsManageSubjectsRoute:
    AuthenticatedSettingsManageSubjectsRoute,
  AuthenticatedSettingsResigninRoute: AuthenticatedSettingsResigninRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  VerifyRoute: VerifyRoute,
  SignupVerifyRoute: SignupVerifyRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
