name: Setup perfin build env
description: setup perfin build env

runs:
  using: "composite"
  steps:
    - name: Setup Node
      id: node
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Configure pnpm cache
      uses: actions/setup-node@v6
      with:
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts
      shell: bash