pnpm wrangler --env production d1 export perfin -y --remote --table='sqlite_sequence' --output='./proddata/sqlite_sequence.sql'
pnpm wrangler --env production d1 export perfin -y --remote --table='d1_migrations' --output='./proddata/d1_migrations.sql'
pnpm wrangler --env production d1 export perfin -y --remote --table='users' --output='./proddata/users.sql'
pnpm wrangler --env production d1 export perfin -y --remote --table='passkeys' --output='./proddata/passkeys.sql'
pnpm wrangler --env production d1 export perfin -y --remote --table='email_codes' --output='./proddata/email_codes.sql'
pnpm wrangler --env production d1 export perfin -y --remote --table='user_devices' --output='./proddata/user_devices.sql'
pnpm wrangler --env production d1 export perfin -y --remote --table='login_attempts' --output='./proddata/login_attempts.sql'
pnpm wrangler --env production d1 export perfin -y --remote --table='accounts' --output='./proddata/accounts.sql'
pnpm wrangler --env production d1 export perfin -y --remote --table='categories' --output='./proddata/categories.sql'
pnpm wrangler --env production d1 export perfin -y --remote --table='expenses' --output='./proddata/expenses.sql'
pnpm wrangler --env production d1 export perfin -y --remote --table='expense_items' --output='./proddata/expense_items.sql'
pnpm wrangler --env production d1 export perfin -y --remote --table='expense_adjustments' --output='./proddata/expense_adjustments.sql'
pnpm wrangler --env production d1 export perfin -y --no-data --remote --table='search_index_versions' --output='./proddata/search_index_versions.sql'
pnpm wrangler --env production d1 export perfin -y --no-data --remote --table='expenses_texts' --output='./proddata/expenses_texts.sql'
pnpm wrangler --env production d1 export perfin -y --no-data --remote --table='sessions' --output='./proddata/sessions.sql'
pnpm wrangler --env production d1 export perfin -y --no-data --remote --table='texts' --output='./proddata/texts.sql'
pnpm wrangler --env production d1 export perfin -y --no-data --remote --table='texts_chunks' --output='./proddata/texts_chunks.sql'
pnpm wrangler --env production d1 export perfin -y --no-data --remote --table='texts_contexts' --output='./proddata/texts_contexts.sql'
pnpm wrangler --env production d1 export perfin -y --no-data --remote --table='expense_refunds' --output='./proddata/expense_refunds.sql'
pnpm wrangler --env production d1 export perfin -y --no-data --remote --table='search' --output='./proddata/search.sql'

cat "./proddata/sqlite_sequence.sql" "./proddata/d1_migrations.sql" "./proddata/users.sql" "./proddata/passkeys.sql" "./proddata/email_codes.sql" "./proddata/user_devices.sql" "./proddata/login_attempts.sql" "./proddata/accounts.sql" "./proddata/categories.sql" "./proddata/expenses.sql" "./proddata/expense_items.sql" "./proddata/expense_adjustments.sql" "./proddata/search_index_versions.sql" "./proddata/expenses_texts.sql" "./proddata/sessions.sql" "./proddata/texts.sql" "./proddata/texts_chunks.sql" "./proddata/texts_contexts.sql" "./proddata/expense_refunds.sql" "./proddata/search.sql" > ./proddata/__combined.sql