DROP INDEX IF EXISTS `idx_expense_refund_expense_id`;
DROP INDEX IF EXISTS `idx_expense_refund_expense_item_id`;
DROP INDEX IF EXISTS `idx_expense_refund_source`;
DROP INDEX IF EXISTS `idx_expenses_texts_sourceId`;
DROP INDEX IF EXISTS `idx_textHash_expenseId`;
DROP INDEX IF EXISTS `idx_search_chunk`;
DROP INDEX IF EXISTS `idx_search_context`;
DROP INDEX IF EXISTS `idx_user_chunks`;
DROP INDEX IF EXISTS `idx_texts_contexts_ctxTextHash_textHash`;
DROP TABLE `expense_refunds`;
DROP TABLE `expenses_texts`;
DROP TABLE `search_index_versions`;
DROP TABLE `search`;
DROP TABLE `texts_chunks`;
DROP TABLE `texts_contexts`;
DROP TABLE `texts`;
ALTER TABLE `expense_items` DROP COLUMN `expense_refund_id`;