-- Sample data generated by ChatGPT

INSERT INTO categories (id, created_at, updated_at, belongs_to_id, name, description, sequence)
VALUES
  ('cat_food',   1730419200, 1730419200, '0iPcrmdtsSRuLvhjmoGNd', 'FOOD',   'Meals and dining',         1),
  ('cat_snacks', 1730419200, 1730419200, '0iPcrmdtsSRuLvhjmoGNd', 'SNACKS', 'Light bites and snacks',   2),
  ('cat_drinks', 1730419200, 1730419200, '0iPcrmdtsSRuLvhjmoGNd', 'DRINKS', 'Beverages',                3);

INSERT INTO expenses (
  id, created_at, updated_at, amount_cents, amount_cents_pre_refund,
  billed_at, belongs_to_id, account_id, category_id, updated_by,
  latitude, longitude, geo_accuracy, shop_name, shop_mall,
  additional_service_charge_percent, is_gst_excluded
) VALUES
-- 1. Food - Din Tai Fung @ VivoCity
('exp1', 1762000000, 1762000000, 2850, 2850,
 1762000000, '0iPcrmdtsSRuLvhjmoGNd', 'acc1', 'cat_food', '0iPcrmdtsSRuLvhjmoGNd',
 1.2645, 103.8222, 15, 'DIN TAI FUNG', 'VIVOCITY',
 NULL, 0),

-- 2. Snacks - Old Chang Kee @ Tampines Mall
('exp2', 1762300000, 1762300000, 180, 180,
 1762300000, '0iPcrmdtsSRuLvhjmoGNd', 'acc1', 'cat_snacks', '0iPcrmdtsSRuLvhjmoGNd',
 1.3531, 103.9456, 10, 'OLD CHANG KEE', 'TAMPINES MALL',
 NULL, 0),

-- 3. Drinks - Starbucks @ Changi Jewel
('exp3', 1762500000, 1762500000, 760, 760,
 1762500000, '0iPcrmdtsSRuLvhjmoGNd', 'sbux', 'cat_drinks', '0iPcrmdtsSRuLvhjmoGNd',
 1.3592, 103.9894, 8, 'STARBUCKS', 'JEWEL CHANGI AIRPORT',
 NULL, 0),

-- 4. Food - McDonalds @ Orchard Lido
('exp4', 1761000000, 1761000000, 920, 920,
 1761000000, '0iPcrmdtsSRuLvhjmoGNd', 'acc1', 'cat_food', '0iPcrmdtsSRuLvhjmoGNd',
 1.3039, 103.8318, 12, 'MCDONALD''S', 'LIDO ORCHARD',
 NULL, 0),

-- 5. Drinks - KOI @ Bugis Junction
('exp5', 1761200000, 1761200000, 580, 580,
 1761200000, '0iPcrmdtsSRuLvhjmoGNd', 'acc1', 'cat_drinks', '0iPcrmdtsSRuLvhjmoGNd',
 1.2995, 103.8551, 10, 'KOI THÉ', 'BUGIS JUNCTION',
 NULL, 0),

('exp6', 1762605000, 1762605000, 1850, 1850,
 1762605000, '0iPcrmdtsSRuLvhjmoGNd', 'acc1', 'cat_food', '0iPcrmdtsSRuLvhjmoGNd',
 1.3592, 103.9894, 7, 'SHAKE SHACK', 'JEWEL CHANGI AIRPORT',
 10, 1),

('exp7', 1762864200, 1762864200, 760, 760,
 1762864200, '0iPcrmdtsSRuLvhjmoGNd', 'sbux', 'cat_drinks', '0iPcrmdtsSRuLvhjmoGNd',
 null, null, 8, 'STARBUCKS', 'NOVENA SQUARE',
 NULL, 0);

INSERT INTO expense_items (
  id, created_at, updated_at, sequence, name, quantity, price_cents,
  expense_id
) VALUES
-- exp1 Din Tai Fung
('item1', 1762000000, 1762000000, 1, 'XIAO LONG BAO', 1, 980, 'exp1'),
('item2', 1762000000, 1762000000, 2, 'FRIED RICE', 1, 1250, 'exp1'),
('item3', 1762000000, 1762000000, 3, 'ICED TEA', 1, 620, 'exp1'),

-- exp2 Old Chang Kee
('item4', 1762300000, 1762300000, 1, 'CURRY PUFF', 1, 180, 'exp2'),

-- exp3 Starbucks
('item5', 1762500000, 1762500000, 1, 'LATTE', 1, 620, 'exp3'),
('item6', 1762500000, 1762500000, 2, 'BLUEBERRY MUFFIN', 1, 140, 'exp3'),

-- exp4 McDonald's
('item7', 1761000000, 1761000000, 1, 'MCSPICY MEAL', 1, 920, 'exp4'),

-- exp5 KOI
('item8', 1761200000, 1761200000, 1, 'MILK TEA', 1, 440, 'exp5'),
('item9', 1761200000, 1761200000, 2, 'GOLDEN BUBBLE TOPPING', 1, 140, 'exp5'),

('item10', 1762605000, 1762605000, 1, 'SHACKBURGER', 1, 950, 'exp6'),
('item11', 1762605000, 1762605000, 2, 'CHEESE FRIES', 1, 600, 'exp6'),
('item12', 1762605000, 1762605000, 3, 'ICED TEA', 1, 300, 'exp6'),

('item13', 1762605000, 1762605000, 3, 'PISTACHIO OATMILK ISL', 1, 860, 'exp7');

