name: Build pull request

on:
  pull_request:
    branches: [ main, production ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup build env
        uses: ./.github/actions/setup

      - name: Typescript Build
        run: pnpm tsbuild