name: Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Typescript Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Typescript Check
        run: pnpm tsbuild

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Run Tests
        run: pnpm test